### ISSUE TITLE
Jodit 5.2.15 edit issues

### ISSUE THREAD

**Issue by sboagy** [sboagy/tunetrees#178]
Moving from jodit-react "^4.1.2" to "^5.2.15" makes the edit mode in Jodit really funky.  CoPilot says:

# Jodit-React Version 4.x to 5.x Color Issues

The major upgrade from jodit-react 4.x to 5.x introduced significant changes to the theming system that are causing your color issues. Here are the key changes and how to fix them:

## Key Changes in Jodit 5.x

1. **CSS Variable System Overhaul**:
   - The CSS variable naming convention changed completely
   - Old variables like `--jd-color-background-default` may no longer exist

2. **Theme Application Method**:
   - The way themes are applied and structured has been reworked
   - The `theme` property now requires proper theme objects

3. **Default Color Palette**:
   - The default color scheme was modified significantly

## Solution

Update your theme configuration to use the new CSS variable system:

```tsx
const config = useMemo(
  () => ({
    id,
    readonly: readOnly,
    theme: isDarkMode ? "dark" : "default",
    // Updated CSS variables for Jodit 5.x
    style: {
      // Remove custom background and other styling that uses old variables
    },
    disablePlugins: ["mobile"],
    // Use built-in themes instead of custom CSS variables
    theme: isDarkMode ? "dark" : "default",
    // Other config remains the same...
    toolbar: false,
    // ...
  }),
  [id, isDarkMode, readOnly]
);
```

## Add Custom CSS for Jodit 5.x

Create or update your CSS file with the new variable structure:

```css
/* AutoResizingRichTextarea.css */
:root {
  /* Light Theme Variables */
  --jodit-color-default: #222;
  --jodit-color-background: #fff;
  --jodit-color-border: #ddd;
  
  /* Other variables as needed */
}

[data-theme="dark"] .jodit-container,
.dark .jodit-container {
  /* Dark Theme Variables */
  --jodit-color-default: #eee;
  --jodit-color-background: #222;
  --jodit-color-border: #444;
  
  /* Other dark theme variables */
}

/* Additional styling for content area */
.jodit-wysiwyg {
  background-color: var(--jodit-color-background);
  color: var(--jodit-color-default);
}
```

## Additional Options

If you're still having issues, you could:

1. **Use external CSS**: Create a more comprehensive CSS file to override Jodit's default styles
2. **Use a different theme plugin**:

```tsx
import "jodit/build/jodit.min.css";
// Import your custom theme CSS after the default CSS

// Then in your config
const config = {
  // Basic configuration
  theme: isDarkMode ? "dark" : "default",
  extraPlugins: ["themePlugin"],
  // ...
};
```

3. **Consider downgrading back to 4.x** if the theming issues are critical and difficult to resolve

Most likely the problem is that the theme system completely changed, and your CSS variables are no longer recognized. Try removing custom styling first and rely on the built-in themes, then gradually add custom styling back once the base is working correctly.
